"use client";

import { useId, useMemo, useState } from "react";

import { destinations, hub, type Destination } from "@/content/delivery-map";
import { LAT_BOTTOM, LAT_TOP, VIEW_H, VIEW_W, landPath } from "@/content/world-map";

/**
 * The delivery map: one hub, an arc to every country with a client behind it.
 *
 * !! THE LAND IS DOTS, WHICH IS A CHOICE AND NOT A COMPROMISE !!
 *
 * A vector coastline would need a real outline file, and a real outline is
 * about a megabyte of coordinates for a decoration nine hundred pixels wide.
 * A dot field is a few kilobytes of polygons rasterised at render, it reads
 * as a map at a glance, and it is already this site's texture: the same dot
 * grid sits behind every hero in components/backgrounds/hero-backdrop.tsx and
 * behind the record panels. A photoreal map would be the one foreign object
 * on the page.
 *
 * !! ALL OF THE LAND IS ONE PATH ELEMENT, AND IT ARRIVES FINISHED !!
 *
 * Every dot is a zero length segment in a single path with a round line cap,
 * which paints a dot per segment: six thousand seven hundred dots, one node.
 *
 * The path is generated by scripts/build-world-outline.mjs and imported from
 * content/world-map.ts. It used to be computed here from the coastline, which
 * meant shipping 26KB gzipped of coordinates and a point in polygon test to
 * every visitor so they could all derive the same string, and deriving it
 * twice: once server side for the HTML, again on hydration. The projection
 * constants are imported from the same file, so the path can never be drawn
 * in a window it was not built for.
 *
 * !! THE ARCS ARE QUADRATIC, BENT AWAY FROM THE HUB !!
 *
 * A straight line between two points on an equirectangular map is not what a
 * route looks like and reads as a diagram. The control point is pushed
 * perpendicular to the chord by a fraction of its length, so the further a
 * destination the more the arc bows, which is roughly what a great circle
 * does on this projection and is what the reference image shows.
 *
 * !! NOTHING MOVES UNTIL A POINTER ASKS IT TO !!
 *
 * There is no idle animation loop. Arcs sit still and dim, and hovering one
 * runs a pulse along it. An ambient animation here would be a permanent
 * repaint behind static text, which is the kind of thing that costs a page
 * its scroll performance for decoration nobody asked to move.
 */


const project = (lng: number, lat: number) => ({
  x: ((lng + 180) / 360) * VIEW_W,
  y: ((LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM)) * VIEW_H,
});

export function DeliveryMap() {
  const uid = useId();
  const [active, setActive] = useState<Destination | null>(null);

  const hubPt = project(hub.lng, hub.lat);

  const arcs = useMemo(
    () =>
      destinations.map((d) => {
        const p = project(d.lng, d.lat);
        const dx = p.x - hubPt.x;
        const dy = p.y - hubPt.y;
        const len = Math.hypot(dx, dy);
        /* Perpendicular to the chord, scaled by its length, so a short hop
           barely bends and a transatlantic one arcs hard. The sign is fixed
           rather than chosen per arc: flipping it per destination made the
           bundle leaving the hub cross itself. */
        const bow = len * 0.22;
        const cx = hubPt.x + dx / 2 + (dy / len) * bow;
        const cy = hubPt.y + dy / 2 - (dx / len) * bow;
        return {
          d,
          p,
          path: `M${hubPt.x.toFixed(1)} ${hubPt.y.toFixed(1)}Q${cx.toFixed(1)} ${cy.toFixed(1)} ${p.x.toFixed(1)} ${p.y.toFixed(1)}`,
          len,
        };
      }),
    [hubPt.x, hubPt.y],
  );

  const activeArc = active ? arcs.find((a) => a.d.code === active.code) : null;

  return (
    <figure className="not-prose">
      {/*
        The text alternative, and since the svg is aria-hidden it is the only
        one. A map is a picture of a list, and the list is the part that has to
        survive for anyone who cannot see it.

        It said "Clients in 49 countries", which is the claim the visible copy
        was moved off when the list went from twelve evidenced countries to the
        full figure. The two have to say the same thing.
      */}
      <figcaption className="sr-only">
        {`The work has reached ${destinations.length} countries from the team in ${hub.name}: ${destinations
          .map((d) => d.name)
          .join(", ")}.`}
      </figcaption>

      <svg
        viewBox={`0 0 ${VIEW_W} ${VIEW_H}`}
        className="w-full h-auto"
        aria-hidden="true"
        onPointerLeave={() => setActive(null)}
      >
        <defs>
          {/* The glow. One filter, reused, rather than a shadow per node. */}
          <filter id={`${uid}-glow`} x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur stdDeviation="2.2" result="b" />
            <feMerge>
              <feMergeNode in="b" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>

        {/* Land. See the note above: one path, a dot per segment. */}
        {/*
          Brand blue at 45 per cent, not the foreground token.

          The land was foreground/25 and read as almost nothing on either
          ground: a quarter of near white on a dark page, a quarter of near
          black on a light one. Both were dust. Blue also puts the map in the
          same family as the arcs crossing it, which is the relationship the
          reference image has, a slate landmass under bright routes, and
          brand.css already flips the token per theme so one value covers both.
        */}
        <path
          d={landPath}
          stroke="currentColor"
          className="text-brand-blue/55"
          strokeWidth={2.4}
          strokeLinecap="round"
          fill="none"
        />

        {/*
          Every route, as a hairline.

          !! THE WEIGHT IS THE WHOLE ARGUMENT HERE, TWICE OVER !!

          These were drawn at 60 per cent and a 1.2 stroke, and forty eight
          arcs leaving one hub at that weight merged into a solid fan: no
          single route could be followed and the landmass underneath
          disappeared. Removing them entirely fixed that and cost something
          real, because a field of unconnected dots does not say the work
          came from one place.

          So they are back at a sixth of the alpha and half the width, which
          is about the lightest a line can be and still resolve. It reads as
          structure rather than as content, the map stays legible through it,
          and the hovered arc has somewhere to stand out from.

          No animation and no filter on these, so forty eight static paths
          cost a paint and nothing per frame.
        */}
        <g fill="none" strokeLinecap="round" className="text-brand-blue/[0.18]">
          {arcs.map(({ d, path }) => (
            <path key={d.code} d={path} stroke="currentColor" strokeWidth={0.6} />
          ))}
        </g>

        {/* The one being pointed at, drawn over the top of them. */}
        {activeArc && (
          <g fill="none" strokeLinecap="round">
            <path
              d={activeArc.path}
              className="text-brand-blue"
              stroke="currentColor"
              strokeWidth={1.6}
            />
            {/*
              The pulse. A short dash chased along the arc by animating the
              offset, which is one property and compositor friendly.
            */}
            <path
              d={activeArc.path}
              stroke="currentColor"
              className="text-brand-blue motion-reduce:hidden"
              strokeWidth={2.4}
              filter={`url(#${uid}-glow)`}
              style={{
                strokeDasharray: `26 ${Math.round(activeArc.len)}`,
                animation: "delivery-pulse 1100ms linear infinite",
                ["--arc-len" as string]: Math.round(activeArc.len + 26),
              }}
            />
          </g>
        )}

        {/*
          Destinations. The hit area is a fat invisible circle, because a three
          pixel dot is not something a pointer can reasonably find.

          !! NO tabIndex AND NO PER DOT LABEL, DELIBERATELY !!

          Each of these carried tabIndex={0} with role="img" and the country
          name, which sounds right and was not. It put forty nine tab stops in
          the middle of the page, so reaching the section below this one meant
          forty nine presses, and a screen reader then read all forty nine
          names twice: once from the labels and once from the figcaption above,
          which already lists every country in a sentence.

          The svg is aria-hidden now and the caption is the whole text
          alternative. That does cost a keyboard visitor the hover, and it is
          the right trade: the arc shows a route to a country the caption has
          already named, so nothing is only available by pointing.

          !! THE GLOW IS TWO CIRCLES, NOT A FILTER !!

          Every one of these had filter="url(#glow)" on it, which is fifty
          filter regions to compose on a page that also has to scroll. A halo
          circle behind the dot costs a fill. The filter is kept for the three
          things that are actually meant to look lit: the hub, the dot being
          pointed at, and the pulse.
        */}
        {arcs.map(({ d, p }) => {
          const on = active?.code === d.code;
          return (
            <g
              key={d.code}
              onPointerEnter={() => setActive(d)}
              onPointerLeave={() => setActive(null)}
              className="cursor-pointer"
            >
              <circle cx={p.x} cy={p.y} r={12} fill="transparent" />
              <circle cx={p.x} cy={p.y} r={on ? 9 : 7} className="fill-brand-blue/20" />
              <circle
                cx={p.x}
                cy={p.y}
                r={on ? 5 : 3}
                className="fill-brand-blue"
                filter={on ? `url(#${uid}-glow)` : undefined}
                style={{ transition: "r 200ms" }}
              />
            </g>
          );
        })}

        {/* The hub, drawn last so it sits over every arc leaving it. */}
        <g>
          <circle cx={hubPt.x} cy={hubPt.y} r={16} className="fill-brand-blue/15" />
          <circle cx={hubPt.x} cy={hubPt.y} r={9} className="fill-brand-blue/30" />
          <circle
            cx={hubPt.x}
            cy={hubPt.y}
            r={4.5}
            className="fill-brand-blue"
            filter={`url(#${uid}-glow)`}
          />
        </g>

        {/* Labels last of all, over everything. The hub is always named; a
            destination names itself only while it is being pointed at. */}
        <Pill x={hubPt.x} y={hubPt.y + 26} text={hub.name} />
        {active && (
          <Pill
            x={project(active.lng, active.lat).x}
            y={project(active.lng, active.lat).y - 20}
            text={active.name}
          />
        )}
      </svg>
    </figure>
  );
}

/**
 * A name on a rounded plate, the way a tooltip reads.
 *
 * !! SVG HAS NO BACKGROUND ON TEXT, SO THE PLATE IS A REAL RECT !!
 *
 * There is no text-background in SVG and no box model to lean on, so the
 * plate has to be drawn and sized by hand, which means knowing how wide the
 * string will be before it renders. Measuring it properly would mean putting
 * it in the DOM, reading it back and drawing a second time.
 *
 * The font makes that unnecessary. These labels are set in JetBrains Mono,
 * where every glyph is exactly 0.6em wide, so the width is the character
 * count times the size times 0.6 and it is exact rather than approximate.
 * Change this to a proportional face and the plate will fit some names and
 * cut others.
 *
 * --secondary is the token: near white on a light ground, the surface tint on
 * a dark one, with --secondary-foreground as the ink either way. That pairing
 * is defined in app/brand.css and is contrast checked there, so the plate
 * cannot end up light on light when the theme flips.
 */
const CHAR_W = 0.6;

function Pill({ x, y, text, size = 12 }: { x: number; y: number; text: string; size?: number }) {
  const padX = 9;
  const w = text.length * size * CHAR_W + padX * 2;
  const h = size + 11;
  return (
    <g style={{ pointerEvents: "none" }}>
      <rect
        x={x - w / 2}
        y={y - h / 2}
        width={w}
        height={h}
        rx={h / 2}
        className="fill-secondary"
      />
      <text
        x={x}
        y={y}
        textAnchor="middle"
        dominantBaseline="central"
        className="fill-secondary-foreground font-mono"
        style={{ fontSize: size }}
      >
        {text}
      </text>
    </g>
  );
}
